// Test-only mock for the `virtual:zmk-layout` module. The real module is
// generated by `codegen/vite-plugin.ts` at build/dev time. Vitest cannot load
// the plugin without pulling parse.ts (which pulls getBoard → virtual-layout →
// virtual:zmk-layout, creating a chicken-and-egg loop at config resolution).
// This file provides a small deterministic dataset so board-profile-dependent
// code paths can execute in unit tests without touching disk.

export const KEYS = [
  { index: 0, x: 0, y: 0, label: 'A', side: 'left', testability: 'keyboard', eventCode: 'KeyA' },
  { index: 1, x: 1, y: 0, label: 'B', side: 'left', testability: 'keyboard', eventCode: 'KeyB' },
  { index: 2, x: 8, y: 0, label: 'C', side: 'right', testability: 'keyboard', eventCode: 'KeyC' },
]

export const ENCODERS = [
  { id: 'left-encoder', label: 'left', side: 'left' },
  { id: 'right-encoder', label: 'right', side: 'right' },
]

export const TESTABLE_KEY_COUNT = 3
